### ISSUE TITLE
Cannot write "property"

### ISSUE THREAD

**Issue by Holraven** [PowershellScripts/SharePointOnline-ScriptSamples#197] opened 2020-11-10 08:13 UTC
When trying to run BlockDownloadOfAllFilesForGuests.ps1:
```
Exception calling "ExecuteQuery" with "0" argument(s): "Oppdatering av denne tenantegenskapen er for øyeblikket deaktiv
ert."
At (...):25 char:3
+   $ctx.ExecuteQuery()
+   ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ServerException
```

Roughly translated to "_updating this tenant property is deactivated for the time being_" (GOD how I wish I could override the language setting). Anything else that need to be enabled on the tenant first?

**Comment by PowershellScripts** [comment] 2020-12-05 18:27
Not that I can think of.

It looks like there might have been some change in design:
https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/suggestions/33755590-blockdownloadofallfilesforguests

and according to Ron and his support ticket, it may have stopped working by design

**Comment by PowershellScripts** [comment] 2021-01-17 14:39
I assume my last comment solved the issue and closing this.

**Closed by PowershellScripts** 2021-01-17 14:39 UTC
